apiVersion: v1
kind: Service
metadata:
  # This name uniquely identifies the service
  name: minio-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 9001
      protocol: TCP
  selector:
    app: minio
---
apiVersion: v1
kind: Service
metadata:
  # This name uniquely identifies the service
  name: minio-read-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: minio
