apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc-claim
  namespace: default
spec:
  storageClassName: storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  volumeName: local-pv
